export enum PropertyState {
  DRAFT = "BORRADOR",
  PENDING = "EN REVISIÓN",
  ACTIVE = "PUBLICADO",
}

export enum PropertyType {
  APARTMENT = "DEPARTAMENTOS",
  HOUSE = "CASAS",
}

export enum PropertyPhase {
  PLANOS = "PLANOS",
  CONSTRUCCION = "EN CONSTRUCCIÓN",
  READY = "ENTREGA INMEDIATA",
}

export enum Permissions {
  MANAGE_PERMISSIONS = "MANAGE_PERMISSIONS",
  MANAGE_ROLES = "MANAGE_ROLES",
  MANAGE_USERS = "MANAGE_USERS",
  VIEW_DICOMS = "VIEW_DICOMS",
  VIEW_TEMPLATES = "VIEW_TEMPLATES",
  GENERATE_REPORT = "GENERATE_REPORT",
  UPLOAD_DICOM = "UPLOAD_DICOM",
  DOWNLOAD_REPORT = "DOWNLOAD_REPORT",
}

export enum PropertyCurrency {
  SOLES = "SOLES",
  DOLARES = "DOLARES",
}
