export enum PropertyState {
  DRAFT = "BORRADOR",
  PENDING = "EN REVISIÓN",
  ACTIVE = "PUBLICADO",
}

export enum PropertyType {
  APARTMENT = "DEPARTAMENTOS",
  HOUSE = "CASAS",
}

export enum PropertyPhase {
  PLANOS = "PLANOS",
  CONSTRUCCION = "EN CONSTRUCCIÓN",
  READY = "ENTREGA INMEDIATA",
}

export enum Permissions {
  MANAGE_PERMISSIONS = "MANAGE_PERMISSIONS",
  MANAGE_ROLES = "MANAGE_ROLES",
  MANAGE_USERS = "MANAGE_USERS",
  VIEW_DICOMS = "VIEW_DICOMS",
  VIEW_TEMPLATES = "VIEW_TEMPLATES",
  GENERATE_REPORT = "GENERATE_REPORT",
  UPLOAD_DICOM = "UPLOAD_DICOM",
  DOWNLOAD_REPORT = "DOWNLOAD_REPORT",
  DELETE_REPORT = "DELETE_REPORT",
  COMPLETE_REPORT = "COMPLETE_REPORT",
  VIEW_NEW_REPORTS = "VIEW_NEW_REPORTS",
  VIEW_VIEWED_REPORTS = "VIEW_VIEWED_REPORTS",
  VIEW_DRAFT_REPORTS = "VIEW_DRAFT_REPORTS",
  VIEW_COMPLETED_REPORTS = "VIEW_COMPLETED_REPORTS",
  CHANGE_TEMPLATE = "CHANGE_TEMPLATE",
}

export enum PropertyCurrency {
  SOLES = "SOLES",
  DOLARES = "DOLARES",
}
