name = "process-dicom"
main = "src/index.ts"
compatibility_date = "2024-01-01"
account_id = "911c03faaa142adbd512d76e6042c0c9"

[[r2_buckets]]
binding = "DICOM_BUCKET"
bucket_name = "dicoms"

[[queues.consumers]]
queue = "dicom-processing"
max_batch_size = 10
max_batch_timeout = 5

[vars]
STORAGE_DOMAIN = "https://storage.cadia.cc"