name = "process-dicom"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[[r2_buckets]]
binding = "DICOM_BUCKET"
bucket_name = "dicoms"

[vars]
STORAGE_DOMAIN = "https://storage.cadia.cc"

[[durable_objects.bindings]]
name = "DICOM_PROCESSOR"
class_name = "DicomProcessor"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["DicomProcessor"]
